# Spring Boot application properties file that are common in all environments
spring:
  application:
    name: demo-spring-boot-application
  profiles:
    active: local
# Common logging properties => the reference is taken from the particular profile which is active
logging:
  file:
    name: ${logging.file.path}/${spring.application.name}.log

#these 3 dashes --- are used as a separator in yaml files
---
# Spring Boot application properties for the local environment
spring:
  config:
    activate:
      on-profile: local
logging:
  file:
    path: logs/local
  logback:
    rollingpolicy:
      max-file-size: 5MB
      file-name-pattern: ${logging.file.name}-%d{yyyy-MM-dd}-%i.log

#these 3 dashes --- are used as a separator in yaml files
---
# Spring Boot application properties for production environment
spring:
  config:
    activate:
      on-profile: prod
logging:
  file:
    path: logs/prod
  logback:
    rollingpolicy:
      max-file-size: 10MB
      file-name-pattern: ${logging.file.name}-%d{yyyy-MM-dd}-%i.log