# Spring Boot application properties file that are common in all environments
#spring-properties
spring.application.name=demo-spring-boot-application
# the below property is used to set the default profile
spring.profiles.active=local
# common logging properties => the reference is taken from the particular profile which is active
logging.file.name=${logging.file.path}/${spring.application.name}.log


