logging:
  file:
    name: ${logging.file.path}/${spring.application.name}.log
    path: logs
  logback:
    rollingpolicy:
      file-name-pattern: ${logging.file.path}/${spring.application.name}-%d{yyyy-MM-dd}-%i.log
      max-file-size: 10MB
spring:
  application:
    name: petistaan
  datasource:
    url: jdbc:h2:mem:petistaan
    username: sa
    password:
    driver-class-name: org.h2.Driver
    initialization-mode: always
  jpa:
    hibernate:
      ddl-auto: none  # Disable Hibernate's DDL generation
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        format_sql: true
  sql:
    init:
      mode: always  # Always initialize the database
      schema-locations: classpath:schema.sql
      data-locations: classpath:data.sql
  h2:
    console:
      enabled: true
      path: /h2-console


# enable H2 console which can be accessed at /h2-console or http://localhost:8080/h2-console