# Spring Boot application properties for production environment
# NOTE THE hyphen in the property name: application"-"prod.properties
logging.file.path=logs/prod
logging.logback.rollingpolicy.max-file-size=10MB
logging.logback.rollingpolicy.file-name-pattern=${logging.file.name}-%d{yyyy-MM-dd}-%i.log