#spring-properties
spring.application.name=demo-spring-boot-application
#logging-properties
logging.file.path=logs
logging.file.name=${logging.file.path}/${spring.application.name}.log
logging.logback.rollingpolicy.max-file-size=10MB
logging.logback.rollingpolicy.file-name-pattern=${logging.file.name}-%d{yyyy-MM-dd}-%i.log
